### ISSUE TITLE
Small typo in "Publishing a Rust CLI to Homebrew"

### ISSUE THREAD

**Issue by craigpastro** [kawamurakazushi/.com#115]
👋 Thanks for the wonderful post. I learned a lot.

To get it to work I had to make one small change to the following line:
```
shasum tle-0.1.0-x86_64-apple-darwin.tar.gz
```
to
```
shasum -a 256 tle-0.1.0-x86_64-apple-darwin.tar.gz
```

Then everything worked perfectly!

**Comment by kawamurakazushi** [comment]
@craigpastro 
thanks! 
I will take a look and update the blog post!
